const offerLink = "vnd.youtube://youtube.com/redirect?event=comments&redir_token=QUFFLUhqbTg5UHlaLW5fSE9manhaczlvVnlwZHhMVmREQXxBQ3Jtc0tsN3JPcnVGVUVNVHpTUmNfOEVGM1JiSnk1TENnTFdSTDFSVWxEcU4tZ2IxcjlyX1puODY2dXdYTFJjLXRSTmxTUklfdlVRMmJkcFNQcWRVZGpQMWpoNmJDRHJGOTlLdmlsQU42T096bGd5a1piWGtfWQ&q=https%3A%2F%2Fcuty.io%2FeoQxr&html_redirect=1 ";

